server:
  port: 8088
spring:
  application:
    name: config-service
  profiles:
    active: composite
  cloud:
    config:
      server:
        composite:
          - type: native
            search-locations: file://${user.home}/config-service
        bootstrap: true